messages:
  prefix: "§x§0§8§4§C§F§BI§x§2§9§6§D§F§Bn§x§4§A§8§F§F§Cv§x§6§B§B§0§F§Ci§x§8§C§D§2§F§Dt§x§A§D§F§3§F§De §r§8» §r"
  no-permission: "§cYou don't have permission to do that."
  reloaded: "§eConfig reloaded."
  invite-nonexistent: "§cThat player doesn't exist."
  invite-invited: "§cThat player has already been invited to the server."
  invite-playing: "§cThat player is already playing on the server"
  invite-success: "§ePlayer %player% will now be able to join the server."
  invite-timeout: "§cYou can invite another player in §e%time%§c."
  only-player: "§cOnly player can invoke this command."

# Number of invites one can make after joining the server, without timeout
instant-invites: 3
# How often can players invite other players after first instant-invites, in ms
timeout: 86400000
# Current implementation consumes a lot of RAM
offline-suggestions: true
# Player name cache survival time, in ms
cache-survival: 10000
# Saves on computation
first-n-suggestions: 5